### ISSUE TITLE
Does not show any browser

### ISSUE THREAD

**Issue by VINTX2** [Browsers-software/browsers#226] opened 2024-09-23 19:39 UTC
**Describe the bug**
I have multiple browsers installed on my system (Firefox, ungoogled Chromium, Mullvad, Tor), but none of them is displayed.

**System:**
 - OS: Arch Linux with Gnome Wayland
 - Browsers Version⋮ Firefox 130.0.1

I have checked the .desktop files and they include `x-scheme-handler/https`

Logs:
```
2024-09-23T21:36:56.091937784+02:00  INFO browsers: Starting Browsers
2024-09-23T21:36:56.091964182+02:00  INFO browsers: Logging to /home/user/.local/state/software.Browsers/logs/browsers.log
2024-09-23T21:36:56.092004757+02:00  INFO browsers::communicate: No other instance of Browsers was running
2024-09-23T21:36:56.092012692+02:00  INFO browsers::communicate: Cleaning up previous local socket file
2024-09-23T21:36:56.092039566+02:00  INFO browsers::communicate: Started socket listener for new instances of Browser
2024-09-23T21:36:56.092135315+02:00  INFO basically_main: browsers::browser_repository: Repository: /usr/share/software.Browsers/resources/repository/application-repository.toml
2024-09-23T21:36:56.112622503+02:00  INFO basically_main: browsers::linux::linux_utils: Default for x-scheme-handler/https is 'software.Browsers.desktop'
2024-09-23T21:36:56.127567609+02:00  INFO basically_main: browsers::linux::linux_utils: Default for x-scheme-handler/http is 'software.Browsers.desktop'
2024-09-23T21:36:56.127603418+02:00  INFO basically_main: browsers::utils: Config: /home/user/.config/software.Browsers/config.json
2024-09-23T21:36:56.127737115+02:00  INFO basically_main: browsers::utils: Config: /home/user/.config/software.Browsers/config.json
2024-09-23T21:36:56.199564782+02:00  INFO basically_main: druid_shell::backend::gtk::application: gtk: Activated application
```

Thank you!

**Comment by liias** [comment] 2024-09-23 20:05
Hey there! Could you try previous version and see if that works?

**Comment by VINTX2** [comment] 2024-09-23 20:36
Tried 0.5.8 and 0.5.6. The issue persists.

**Comment by liias** [comment] 2024-09-24 17:27
There was a regression in 0.5.9. Please try 0.6.0.

After running it make sure you click on "Refresh" in "..." menu.
Also make sure version name is 0.6.0 in "..."->"About" dialog.

**Comment by VINTX2** [comment] 2024-09-24 18:52
It works now, thank you!

I have noticed a few more problems. Should I submit a new issue?

- it does not open the links I click on, but rather opens the url `file:///home/user/`
- the config file at `~/.config/software.Browsers/config.json` is incomplete. I wanted to change the order of the browsers.
```
 1 {
 2   "hidden_apps": [],
 3   "hidden_profiles": [],
 4   "profile_order": [],
 5   "default_profile": null,
 6   "rules": [],
 7   "ui": {
 8     "show_hotkeys": true,
 9     "quit_on_lost_focus": false,
10     "theme": "Auto"
11   },
12   "behavior": {
13     "unwrap_urls": false
14   }
15 }
```
- the app window is not opening at the cursor position under Gnome Wayland. It does under Gnome Xorg.

**Comment by liias** [comment] 2024-10-01 21:03
> I have noticed a few more problems. Should I submit a new issue?

Let's see if we can resolve any here first.

> - it does not open the links I click on, but rather opens the url `file:///home/user/`

Weird I can't reproduce that. Does it show correct url in the bottom bar?

> - the config file at `~/.config/software.Browsers/config.json` is incomplete. I wanted to change the order of the browsers.
> 
> ```
> 
>  1 {
> 
>  2   "hidden_apps": [],
> 
>  3   "hidden_profiles": [],
> 
>  4   "profile_order": [],
> 
>  5   "default_profile": null,
> 
>  6   "rules": [],
> 
>  7   "ui": {
> 
>  8     "show_hotkeys": true,
> 
>  9     "quit_on_lost_focus": false,
> 
> 10     "theme": "Auto"
> 
> 11   },
> 
> 12   "behavior": {
> 
> 13     "unwrap_urls": false
> 
> 14   }
> 
> 15 }
> 
> ```
> 
Implicit/default order is not stored in config file. You can try reordering by just right clicking on the item. Then you can also reorder in config file.


> - the app window is not opening at the cursor position under Gnome Wayland. It does under Gnome Xorg.

Where does it open instead?

**Comment by VINTX2** [comment] 2024-10-03 10:51
> > * it does not open the links I click on, but rather opens the url `file:///home/user/`
> 
> Weird I can't reproduce that. Does it show correct url in the bottom bar?

No, the bottom bar of the browsers window is empty.
I have noticed that it opens the URL `file:///home/user/` only when I select a browser based on Firefox.
When I select Chromium, it opens an empty tab.

> > * the app window is not opening at the cursor position under Gnome Wayland. It does under Gnome Xorg.
> 
> Where does it open instead?

In the top left corner of the desktop.
It may not be possible to solve this. This issue with Wayland exists for years.

There is a similar app, which could not solve this.
https://github.com/sonnyp/Junction/issues/35

**Comment by liias** [comment] 2024-10-03 12:29
> No, the bottom bar of the browsers window is empty.
> I have noticed that it opens the URL file:///home/user/ only when I select a browser based on Firefox.
> When I select Chromium, it opens an empty tab.

What happens when you run it from command line together with some url, e.g: `browsers https://github.com`?
Do you use the default `software.Browsers.desktop` file - does it have `%u` in the end in the `Exec` value?

**Comment by VINTX2** [comment] 2024-10-03 12:43
The `%u` was missing in the .desktop file. Now it works, thank you!

I did not change the .desktop file. I have installed the browsers-git package through the Arch User Repository.

**Comment by liias** [comment] 2024-10-03 13:18
> The `%u` was missing in the .desktop file. Now it works, thank you!
> 
> I did not change the .desktop file. I have installed the [browsers-git](https://aur.archlinux.org/packages/browsers-git) package through the Arch User Repository.

Great to hear it works now!
@Kimiblock - sorry for bumping out of nowhere - any chance it could be added in the aur repo?

@VINTX2 - I will now close this issue. Feel free to create a separate one for window position in Gnome Wayland. Please also report Gnome and Wayland versions there if you do.

**Closed by liias** 2024-10-03 13:18 UTC
Labels: Linux

**Comment by Kimiblock** [comment] 2024-10-09 15:17
Hi, add what to the AUR repo?


--
Sincerely, 
Kimiblock

**Comment by liias** [comment] 2024-10-09 19:05
> Hi, add what to the AUR repo?
> […](#)
> -- Sincerely, Kimiblock

Hey there!

Basically, adding `%u` at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=browsers-git#n45 so a web link is passed from desktop environment to browsers as an argument

So, from
```
sed -i 's/€ExecCommand€/browsers/g'
```
to
```
sed -i 's/€ExecCommand€/browsers %u/g'
```
