### ISSUE TITLE
Multiple Firefox profiles not detected or displayed

### ISSUE THREAD

**Issue by awkto** [Browsers-software/browsers#81] opened 2023-07-27 01:26 UTC
**Describe the bug**

I have 2 firefox profiles, but only one is displayed in the Browsers popup.

**System:**
Fedora Workstation 38
Firefox installed natively (not snap or flatpak)

**Comment by liias** [comment] 2023-07-27 08:28
Hi. Could you also attach a screenshot?

**Comment by awkto** [comment] 2023-07-27 09:04
![image](https://github.com/Browsers-software/browsers/assets/89759210/b7a7f762-beed-468f-814a-a983875f5f0b)

**Comment by awkto** [comment] 2023-07-27 09:16
![image](https://github.com/Browsers-software/browsers/assets/89759210/e5a8d16c-a0df-4b73-b8dc-a47edce7780a)

**Comment by liias** [comment] 2023-07-27 11:58
I see. There is no profile name in the Firetox option in Browsers. This means Browsers doean't recognize it as Firefoz but just "some browser".

It identifies Firefox by the .desktop file name right now. Could you find out the name of the .desktop file that Firefox uses in your distro?

**Comment by yacc143** [comment] 2023-09-14 12:31
```
[andreas@amnesix ~]$ rpm -ql firefox | grep desktop
/usr/share/applications/firefox.desktop
```
That is from Fedora 37, but I do share the symptoms.
[firefox.txt](https://github.com/Browsers-software/browsers/files/12608763/firefox.txt)

**Comment by liias** [comment] 2024-01-31 19:05
Sorry for never getting back to this. The name and content of the desktop file looks correct. 
Does the problem still exist?

**Comment by liias** [comment] 2024-02-01 16:15
Hey! The original issue is slightly different - about seeing **no** profiles.

Do you refer to `default-release` profile being missing?

If it happens again, please share your `profiles.ini`

**Comment by psydvl** [comment] 2024-02-01 18:37
Yes, `default-release` is missing
When I deleting `install.ini` and items in `profiles.ini`, `Browsers` sees all profiles
But on next Firefox launch everything broke again 
Files:
[installs.txt](https://github.com/Browsers-software/browsers/files/14129469/installs.txt)
[profiles.txt](https://github.com/Browsers-software/browsers/files/14129470/profiles.txt)

**Comment by liias** [comment] 2024-02-01 19:07
Which Linux distribution do you use?
How is Firefox package installed? apt/snap/something else?

**Comment by psydvl** [comment] 2024-02-01 19:16
openSUSE Slowroll (Tumbleweed)
zypper (I think rpm is builds somewhere here: https://build.opensuse.org/package/show/openSUSE:Factory/MozillaFirefox)
```
$ firefox --full-version 
Mozilla Firefox 121.0.1 20240108143603 20240108143603 
```

**Comment by liias** [comment] 2024-02-01 19:46
Could you try out this experimental build - https://nightly.link/Browsers-software/browsers/workflows/ci/firefox-ignore-lock

(it will be ready once https://github.com/Browsers-software/browsers/actions/runs/7746747952 finishes)

**Comment by psydvl** [comment] 2024-02-01 19:51
CI failed for linux :)

**Comment by liias** [comment] 2024-02-01 20:35
> CI failed for linux :)

Oop, sometimes GH fails with their cache, fixed

**Comment by psydvl** [comment] 2024-02-01 21:02
Nightly shows only Firefox without profiles

<details><summary>tar.gz browsers-nightly after refresh</summary>
<p>

![image](https://github.com/Browsers-software/browsers/assets/43755002/94e3e177-07cd-4283-ac0c-274316cd2f8e)

If select in profile appears `"profile": "firefox#",`

When opens with nightly with that config opens firefox main profile
When opens with 0.5.1 with that config opens firefox ProfileManager

</p>
</details> 

<details><summary>tar.gz browsers-0.5.1 same as rpm installed after refresh</summary>
<p>

![image](https://github.com/Browsers-software/browsers/assets/43755002/07812ad8-a0bc-47f0-8abc-179a80fb9c94)

If select in profile appears `"profile": "firefox#tmp",`

</p>
</details> 

<details><summary>Firefox Profiles</summary>
<p>

![image](https://github.com/Browsers-software/browsers/assets/43755002/a2720a1a-9d18-42b5-bb0b-da4ceae061ac)

</p>
</details>

**Comment by liias** [comment] 2024-02-05 17:34
Thanks for reporting back!

Could you also attach the logs (logs directory is visible in About dialog and also Settings...->Advanced->Directories? Please also refresh the profiles before.

**Comment by liias** [comment] 2024-02-08 18:15
> Nightly shows only Firefox without profiles
This is probably caused by the fact that linux binary assumes resources are relative to the executable at `../resources/...`

0.5.2 is now released with the same fix, let me know if all Firefox profiles show up if installing the release version.

**Comment by psydvl** [comment] 2024-02-08 18:57
Fixed for me, thank you

**Closed** 2024-02-08 20:05 UTC
Labels: Linux, waiting for feedback
