### ISSUE TITLE
Icon-related crash on Linux regression of #12

### ISSUE THREAD

**Issue by joefiorini** [Browsers-software/browsers#90] opened 2023-08-21 15:24 UTC
**Describe the bug**
Crash on KDE Plasma 5.27.6, same crash as in #12 but different line number:

<details><summary>Output from running /usr/bin/browsers at command line</summary>
<p>
<pre>
2023-08-21T11:13:13.314774014-04:00  INFO browsers: Starting Browsers
2023-08-21T11:13:13.314801798-04:00  INFO browsers: Logging to /var/home/joe/.local/state/software.Browsers/logs/browsers.log
2023-08-21T11:13:13.314840647-04:00  INFO browsers::communicate: No other instance of Browsers was running
2023-08-21T11:13:13.314974386-04:00  INFO browsers::communicate: Started socket listener for new instances of Browser
Gtk-Message: 11:13:13.383: Failed to load module "colorreload-gtk-module"
2023-08-21T11:13:13.406281647-04:00  INFO browsers::linux_utils: icon: from /var/lib/flatpak/exports/share/icons/hicolor/512x512/apps/com.slack.Slack.png to /var/home/joe/.cache/software.Browsers/icons/com.slack.Slack.desktop.png
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/linux_utils.rs:196:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:117:5
   3: browsers::linux_utils::OsHelper::get_installed_browsers
   4: browsers::generate_all_browser_profiles
   5: browsers::basically_main
   6: browsers::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</pre>
</p>
</details> 

**System:**
 - OS: Fedora Kinoite 38
 - Browsers Version [e.g. 0.22.1] `⋮` -> About: 0.4.1

FYI there's a line in the log that says:

> tk-Message: 11:13:13.383: Failed to load module "colorreload-gtk-module"

I see that with any GTK app I run and so far it's been safe to ignore it. Doesn't mean it's not related, but I wouldn't put a lot of stock in it either.

**Comment by joefiorini** [comment] 2023-08-21 16:42
Spoke too soon. Now I'm getting this error:

(browsers:745667): GLib-GIO-CRITICAL **: 12:41:05.385: This application can not open files.

I was running directly from the build directory with `./targets/release/browsers http://duckduckgo.com`

**Comment by liias** [comment] 2023-08-31 19:17
Hey, @joefiorini 
I added better handling for the missing icon, so it should not crash for that reason anymore if compiling from `main`.

About the new crash - is there any stacktrace involved? I tried Fedora Kinoite 38, and 'm not able to reproduce this issue.

**Comment by liias** [comment] 2024-01-27 18:10
Closing. Please reopen if anyone has same issue.

**Closed as completed by liias** 2024-01-27 18:10 UTC
Labels: bug, Linux, waiting for feedback
