### ISSUE TITLE
%THIS_DIR% not always set correctly. Uncaught error.

### ISSUE THREAD

**Issue by Erquint** [Browsers-software/browsers#116] opened 2023-12-24 19:19 UTC
Renamed the directory to `Browsers!`.
Ran the install script in Windows 10 → Elevated Windows Terminal → PowerShell Core (`pwsh`)
```pwsh
PS E:\Programs\Utils\Browsers!> .\install.bat
Starting Installation
Because you are running this as an administrator we are going to install it to the whole system

The argument 'E:\Programs\Utils\Browsers\announce_default.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Browsers has been installed. Enjoy
Please report any issues at https://github.com/Browsers-software/browsers/issues
You can now press Enter to exit this installer.
```
The script looked for a path without `!` and thus failed to execute the PS script.
The error was not caught and handled.
The script falsely reports success.
This isn't good.

`install.bat`
```CMD
REM .bat location with trailing \
set THIS_DIR=%~dp0
[…]
powershell -ExecutionPolicy Bypass -File "%THIS_DIR%announce_default.ps1"
```
Seems like `%~dp0` returns the wrong path.

**Comment by Erquint** [comment] 2023-12-24 19:56
While the above is an issue of its own to be resolved, I have tried recovering from it…
Renamed the directory containing the installer to `Browsers`. Installed again. Seemed to install fine.
Tried associating and launching — the association uses some nonexistent path. I'm investigating further…

**Comment by liias** [comment] 2023-12-27 15:50
Hi, Murad, I hope you are surviving the holiday season! So let's get to it.

First of all, thank you for looking so deeply into this!

**Problem 1: Missing `!` in path**
`install.bat` script has enabled [Delayed Expansion](https://ss64.com/nt/delayedexpansion.html), which is a Windows Batch Script feature to "expand" variables to values during execution time. In our case, that allows using local variables scoped to an if-block, and actually reference to that variable in that same if block. Referencing a variable via delayed expansion is done with `!var-name! instead of the usual `%var-name%`.

But you discovered a bug - having delayed expansion enabled also strips `!` characters when expanding `%~dp0` value into `THIS_DIR`.
Because we don't actually need delayed expansion at that point, I will toggle it on only in places where it's needed.

**Problem 2: Install script continues after failed step**
Unfortunately Windows Batch has no global flag to exit script whenever any command fails and I forgot to validate that part (as the script doesn't really do anything besides printing after that command).

**Problem 3: Missing uninstaller**
I recently added it for linux and it makes sense to also add it for Windows. Added to backlog.

**Problem 4: wrong path in Registry for system-wide install**
Did the developer even test this??!!?? It's broken for system-wide install and needs to be fixed.

**Problem 5: script incorrectly detects that admin is running it**
I'm using this "hack" to detect if current is admin: https://superuser.com/questions/667607/check-if-current-command-prompt-was-launched-as-the-administrator so there can be some condition met, where it really thinks you are admin, because you can access `%windir%\system32\config\systemprofile` without any problems.

**Problem 6: application crashes at launch**
Hmm, you are the 3rd person having it [crashing](https://github.com/Browsers-software/browsers/issues/69#issuecomment-1696553407), but you are the first one with error trace. Thank you!

I will go through all of them to fix them. But the last (and most important bug) might need more troubleshooting.

But to be honest, Windows release is least tested and lacks the most features. I might pull it off from Download section or mark it with alpha tag.

**Comment by Erquint** [comment] 2024-01-14 14:27
1. Curious.
2. Manual guarding in control flow required as it often is.
3. What a lot of projects without ready uninstallers do is list the deployments in the readme so that the user can remove them manually. I ended up intuiting on it but same can't be expected of all users…
4. Without looking at the code, it might be related to the elevation detection. But there must be more to it than that.
5. Yeah, well, that's what you get for checking a functionally irrelevant trait — not the one the execution of the script is actually going to depend on. And Linux way doesn't quite apply there. I find the `whoami /groups | find "S-1-16-12288"` more fitting if you wanna stay in CMD land. However, in __Windows PoweShell__ (`powershell`) you could use .NET invocations to evaluate a conditional like this: `if((New-Object System.Security.Principal.WindowsPrincipal([System.Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)){"bark"}else{"meow"}`. Unsure if there's any good way in __PowerShell Core__ (`pwsh`).
7. Sorry I can't help further than that with the crash. Gone and installed Hurl — turned out to suit my needs nicely.

Wish I could say I'd look into the code, but not really ready to contribute at the moment and it's been a while since I used CMD other than as a PowerShell Core launcher. It's a shame PowerShell Core adoption is so militantly rejected in Linux realm — otherwise you could perhaps realistically target it as a cross-platform shell.

**Comment by liias** [comment] 2024-01-18 22:24
> 1. Curious.
> 2. Manual guarding in control flow required as it often is.
> 3. What a lot of projects without ready uninstallers do is list the deployments in the readme so that the user can remove them manually. I ended up intuiting on it but same can't be expected of all users…
> 4. Without looking at the code, it might be related to the elevation detection. But there must be more to it than that.
> 5. Yeah, well, that's what you get for checking a functionally irrelevant trait — not the one the execution of the script is actually going to depend on. And Linux way doesn't quite apply there. I find the `whoami /groups | find "S-1-16-12288"` more fitting if you wanna stay in CMD land. However, in **Windows PoweShell** (`powershell`) you could use .NET invocations to evaluate a conditional like this: `if((New-Object System.Security.Principal.WindowsPrincipal([System.Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)){"bark"}else{"meow"}`. Unsure if there's any good way in **PowerShell Core** (`pwsh`).
> 6. Sorry I can't help further than that with the crash. Gone and installed Hurl — turned out to suit my needs nicely.
> 
> Wish I could say I'd look into the code, but not really ready to contribute at the moment and it's been a while since I used CMD other than as a PowerShell Core launcher. It's a shame PowerShell Core adoption is so militantly rejected in Linux realm — otherwise you could perhaps realistically target it as a cross-platform shell.

Hey there,
Aspects 1-4 should be fixed in latest version.
Thanks for the pointer on (5), I will take a look at it again if anyone reports an issue.
The main issue (6), I haven't reproduced, but if there are enough interest in Windows, someone will stumble on it again.

And no problem, hope Hurl works out fine for you!

**Comment by liias** [comment] 2024-01-27 18:12
As most of the issues should be solved, I'm closing this issue and wait for someone to create a new one if they can reproduce it.

**Closed by liias** 2024-01-27 18:12 UTC
Labels: Windows
